"use client";

import Link from "next/link";
import { ShieldCheck } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

function Status({ name, status, children }: { name: string; status: string; children: React.ReactNode }) {
  return <Card><CardHeader><CardTitle className="flex flex-wrap items-center justify-between gap-2 text-xl text-accent"><span>{name}</span><span className="rounded-full border border-cyan-300/30 bg-cyan-950/40 px-3 py-1 text-xs uppercase tracking-wider text-cyan-200">{status}</span></CardTitle></CardHeader><CardContent className="text-sm leading-6 text-foreground/90 sm:text-base">{children}</CardContent></Card>;
}

export default function TransparencyStatementPage() {
  return <main className="container mx-auto px-3 py-6 sm:px-6">
    <header className="mb-6">
      <h1 className="flex items-center text-3xl font-headline text-primary sm:text-4xl"><ShieldCheck className="mr-3 h-9 w-9" />Game Economy & Support Transparency</h1>
      <p className="mt-2 text-muted-foreground">What exists now, what is experimental and what is not offered.</p>
      <p className="mt-1 text-xs text-muted-foreground">Last updated: 7 October 2026</p>
    </header>
    <div className="space-y-5">
      <Status name="Vanguard Credits, Astralyte and Points" status="Live game features">
        <p>These are fictional in-game resources earned or used for gameplay and progression. They are not cryptocurrency, money, investments or redeemable rewards. They cannot currently be withdrawn or transferred to another wallet or player.</p>
      </Status>
      <Status name="Tap Tap and arcade rewards" status="Gameplay only">
        <p>Rewards generated by Tap Tap or other minigames affect game progress only. Scores and credits do not represent income and do not promise financial return.</p>
      </Status>
      <Status name="Wallet connection" status="Experimental">
        <p>The interface may allow a player to connect a compatible wallet. Connection alone does not initiate payment, create a token, prove ownership of game content or grant currency. Never send us a seed phrase or private key.</p>
      </Status>
      <Status name="Smart contracts, tokens and NFTs" status="Not active">
        <p>Mission: Vanguard currently has no official cryptocurrency, deployed smart contract or official NFT collection. There is no contract address to buy from. Any person claiming otherwise is not describing the current official release.</p>
      </Status>
      <Status name="Ko-fi support" status="Active">
        <p>Any contribution helps support continued development. The Founding Commander Pack is a supporter purchase providing cosmetic recognition and a chosen name in the credits. It does not provide equity, project ownership, revenue share, profit, interest, investment returns or blockchain assets.</p>
      </Status>
      <Status name="Telegram payments" status="Not active">
        <p>Telegram Stars may be considered for future digital cosmetic purchases. No such purchase system is active until it is implemented, tested and covered by updated terms and support procedures.</p>
      </Status>
      <Status name="Future changes" status="No promise">
        <p>Ideas on a roadmap are not guaranteed features. Before introducing real-money purchases, blockchain assets or material data collection, we will publish updated information and obtain any consent required by law.</p>
      </Status>
      <Card><CardHeader><CardTitle className="text-xl text-accent">Questions or suspicious claims</CardTitle></CardHeader><CardContent className="space-y-2 text-sm leading-6 text-foreground/90 sm:text-base"><p>Contact Pilukarts Studio at <a className="text-primary hover:underline" href="mailto:pilukartsstudio@gmail.com">pilukartsstudio@gmail.com</a>.</p><p>Read the <Link className="text-primary hover:underline" href="/legal/terms-of-service">Terms</Link> and <Link className="text-primary hover:underline" href="/legal/privacy">Privacy Notice</Link>.</p></CardContent></Card>
    </div>
  </main>;
}
