name: Send file to Telegram on push

on:
  push:
    branches:
      - main

jobs:
  send_telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install python-telegram-bot
        run: pip install "python-telegram-bot>=13.15,<20.0"

      - name: Send file to Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python -c "
          import os
          from telegram import Bot

          token = os.environ.get('TELEGRAM_TOKEN')
          chat_id = os.environ.get('TELEGRAM_CHAT_ID')

          if not token:
              raise ValueError('TELEGRAM_TOKEN is not set.')
          if not chat_id:
              raise ValueError('TELEGRAM_CHAT_ID is not set.')

          bot = Bot(token)
          bot.send_message(chat_id=chat_id, text='Hello from GitHub Actions!')

          # Para enviar un archivo en lugar de un mensaje, descomenta y usa la línea de abajo:
          # bot.send_document(chat_id=chat_id, document=open('yourfile.txt', 'rb'))
          "
